# Generated by Django 5.0.1 on 2024-01-03 11:07

import django.db.models.deletion
import vehicle_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=220)),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('model_year', models.IntegerField(default=2000, validators=[vehicle_management.models.validate_model_year])),
                ('shape', models.CharField(max_length=4)),
                ('auction_grade', models.CharField(max_length=200)),
                ('package', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_capacity', models.IntegerField(default=1)),
                ('origin_country', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('company_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_quantity', models.IntegerField(default=0, editable=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('vehicle_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicledetails')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicleseries')),
            ],
        ),
        migrations.CreateModel(
            name='OtherVehicleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('vehicle_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicleprice')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('availability_status', models.CharField(choices=[('Empty', 'Empty'), ('Port', 'Port'), ('Onship', 'Onship'), ('Inhouse', 'Inhouse'), ('Workshop', 'Workshop'), ('Other', 'Other')], default='Empty', max_length=20)),
                ('port_location', models.CharField(blank=True, max_length=200, null=True)),
                ('shed_number', models.TextField(blank=True, null=True)),
                ('onship', models.TextField(blank=True, null=True)),
                ('inhouse_address', models.TextField(blank=True, null=True)),
                ('workshop_address', models.TextField(blank=True, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('vehicle_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicledetails')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicleseries')),
            ],
        ),
    ]
